import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1️⃣ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 2️⃣ Activate App Check (DEBUG mode)
  await FirebaseAppCheck.instance.activate(
    providerApple: AppleDebugProvider(), // Use AppleAppAttestProvider() for production later
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Counter',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Firebase Counter Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final String _docId = 'my_first_counter';

  @override
  void initState() {
    super.initState();
    _loadCounter();
  }

  // Load counter value from Firestore
  Future<void> _loadCounter() async {
    try {
      final doc = await _firestore.collection('counters').doc(_docId).get();
      if (doc.exists) {
        setState(() {
          _counter = doc['count'] ?? 0;
        });
      }
    } catch (e) {
      debugPrint('Error loading counter: $e');
    }
  }

  // Increment counter safely using transaction
  Future<void> _incrementCounter() async {
    try {
      await _firestore.runTransaction((transaction) async {
        final ref = _firestore.collection('counters').doc(_docId);
        final snapshot = await transaction.get(ref);

        final current = snapshot.exists ? snapshot['count'] ?? 0 : 0;
        transaction.set(ref, {
          'count': current + 1,
          'updatedAt': FieldValue.serverTimestamp(),
        });
      });

      setState(() {
        _counter++;
      });
    } catch (e) {
      debugPrint('Error incrementing counter: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
